ipv6: true
dns:
  enable: false
  ipv6: true
  listen: 0.0.0.0:8054
  enhanced-mode: redir-host
  nameserver:
    #- 127.0.0.1:8051
    - 223.6.6.6
    - 114.114.115.115
    # - tls://dns.rubyfish.cn:853
    # - https://dns.rubyfish.cn/dns-query
    # - https://dns.alidns.com/dns-query
  fallback:
    #- 127.0.0.1:8052
    #- https://dns.google/dns-query
    #- https://1.1.1.1/dns-query
    # - tcp://8.8.8.8:53
    # - tcp://8.8.4.4:53
    - tcp://208.67.222.222:443
    - tcp://208.67.220.220:443
    - tls://1.0.0.1:853
    - tls://dns.google:853
    # - tls://dns.google
    # - https://dns.rubyfish.cn/dns-query
    # - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
#proxies:
proxy-groups:
  - name: B0
    type: select
    proxies: [Z1,A1,RZA,FZ,DIRECT]
  - name: A0
    type: select
    proxies: [A1,Z1,RZA,FZ,DIRECT]
  - name: FZ
    type: fallback
    proxies: [RZA,A1]
    interval: 600
    url: https://www.gstatic.com/generate_204
  - name: RZA
    type: relay
    proxies: [A1,Z1]
  - name: Z1
    type: select
    use: [ps]
    proxies: [DIRECT]
  - name: A1
    type: load-balance
    use: [ps]
    strategy: round-robin
    interval: 600
    url: https://www.gstatic.com/generate_204
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/speed.yaml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: https://www.gstatic.com/generate_204
rules:
  - GEOIP,CN,DIRECT
  #- SRC-IP-CIDR,127.0.0.0/8,B0
  #- SRC-IP-CIDR,192.168.123.6/32,B0
  - MATCH,A0
