ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_112420222c78-146"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.232.167.71, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.232.167.71_112420222c78-147"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-148"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_112420222c78-149"}
- {alterId: 0, cipher: auto, port: 31372, server: 106.55.234.95, tls: false, type: vmess, uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411,"name":"CN_106.55.234.95_112820224555-151"}
- {cipher: chacha20-ietf, obfs: plain, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '51760:LLL090ui8oll8', server: 116.162.120.26, type: ssr,"name":"CN_116.162.120.26_112820224555-152"}
- {password: xxoo, port: 443, server: 194.156.99.39, skip-cert-verify: true, type: trojan,"name":"CN_194.156.99.39_11292022e380-155"}
- {alterId: 4, cipher: auto, network: ws, port: 13156, server: 106.12.168.13, tls: false, type: vmess, uuid: 9bf4cba4-9e9e-4da4-8e65-f7c487c539df, ws-opts: {path: /},"name":"CN_106.12.168.13_11292022e380-156"}
- {alterId: 0, cipher: auto, network: tcp, port: 9028, server: 116.129.254.184, skip-cert-verify: true, type: vmess, uuid: 3346872e-3104-3c5b-8f6f-4b809309fa8d, ws-opts: {path: /},"name":"CN_116.129.254.184_11282022b4e9-594"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.24, type: ssr,"name":"CN_116.162.120.24_11292022394f-1119"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.28, type: ssr,"name":"CN_116.162.120.28_11292022394f-1122"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.29, type: ssr,"name":"CN_116.162.120.29_11292022394f-1123"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.31, type: ssr,"name":"CN_116.162.120.31_11292022394f-1124"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 564, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.43, type: ssr,"name":"CN_116.162.120.43_11292022394f-1128"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.49, type: ssr,"name":"CN_116.162.120.49_11292022394f-1132"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.50, type: ssr,"name":"CN_116.162.120.50_11292022394f-1133"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 564, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.59, type: ssr,"name":"CN_116.162.120.59_11292022394f-1134"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '51809:111111', server: 116.162.120.60, type: ssr,"name":"CN_116.162.120.60_11292022394f-1140"}
