ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {password: xxoo, port: 443, server: 194.156.99.39, skip-cert-verify: true, type: trojan,"name":"CN_194.156.99.39_112620220abf-3281"}
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_112420222c78-102"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.232.167.71, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.232.167.71_112420222c78-103"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-104"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_112420222c78-105"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.234.84.132, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.234.84.132_112420222c78-106"}
- {alterId: 0, cipher: auto, port: 31372, server: 106.55.234.95, tls: false, type: vmess, uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411,"name":"CN_106.55.234.95_11252022316d-107"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: official.taipeicitygovernment.com.ua, skip-cert-verify: true, type: trojan,"name":"CN_116.192.173.72_112620222010-108"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 562, protocol: auth_aes128_md5, protocol-param: '27445:jgjgjgjgjgjg', server: 116.162.120.31, type: ssr,"name":"CN_116.162.120.31_112620222d24-112"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '27445:jgjgjgjgjgjg', server: 116.162.120.28, type: ssr,"name":"CN_116.162.120.28_112620222d24-113"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '27445:jgjgjgjgjgjg', server: 116.162.120.30, type: ssr,"name":"CN_116.162.120.30_112620222d24-115"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: 116.192.160.86, skip-cert-verify: true, type: trojan,"name":"CN_116.192.160.86_112620222010-173"}
- {alterId: 1, cipher: auto, network: ws, port: 50205, server: data-hk-v2.shwjfkw.cn, tls: false, type: vmess, uuid: b1478e24-4916-3abe-8f17-15931012ecbe, ws-opts: {path: /hls/cctv5phd.m3u8},"name":"CN_58.32.42.56_112620220abf-660"}
