ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_11292022e5f5-104"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-105"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.234.84.132, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.234.84.132_12032022e2e7-106"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_12042022c941-107"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '32329:ff112233', server: 116.162.120.51, type: ssr,"name":"CN_116.162.120.51_12042022c941-108"}
- {alterId: 0, cipher: auto, network: ws, port: 5888, server: a976632911.fun, tls: false, type: vmess, uuid: 294eecf0-1194-4007-aa23-653099029a82, ws-opts: {path: /},"name":"CN_27.41.247.46_120420220fa5-109"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 560, protocol: auth_aes128_md5, protocol-param: '32329:ff112233', server: 116.162.120.28, type: ssr,"name":"CN_116.162.120.28_12042022c941-110"}
- {alterId: 0, cipher: auto, port: 31372, server: 106.55.234.95, tls: false, type: vmess, uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411,"name":"CN_106.55.234.95_1205202212bc-111"}
- {alterId: 64, cipher: auto, port: 19889, server: 117.50.172.89, tls: false, type: vmess, uuid: 8830f9ba-b300-419f-92fc-dd5b5b82da6f,"name":"CN_117.50.172.89_12052022bdf4-329"}
- {alterId: 0, cipher: auto, network: ws, port: 443, server: 113.31.124.147, tls: true, type: vmess, uuid: 91646f9a-b4e9-4aca-bfe3-8892b3e58fe7, ws-opts: {path: /ray},"name":"CN_113.31.124.147_12052022bdf4-662"}
- {alterId: 0, cipher: auto, network: ws, port: 63082, server: in05.my1188.org, tls: false, type: vmess, uuid: c1517df4-6454-39ce-9037-d5eccfc703b7, ws-opts: {path: /},"name":"CN_223.167.41.68_12052022bdf4-666"}
- {alterId: 0, cipher: auto, network: ws, port: 63086, server: in04.my1188.org, tls: true, type: vmess, uuid: c1517df4-6454-39ce-9037-d5eccfc703b7, ws-opts: {path: /mugua},"name":"CN_2409:8c54:6818::1:1051:1b6_12052022bdf4-669"}
- {alterId: 0, cipher: auto, network: ws, port: 443, server: 106.75.218.112, tls: true, type: vmess, uuid: 91646f9a-b4e9-4aca-bfe3-8892b3e58fe7, ws-opts: {path: /ray},"name":"CN_106.75.218.112_120620228f77-673"}
- {password: ba4fedf8c217c146, port: 3389, server: 120.236.197.205, skip-cert-verify: false, type: trojan,"name":"CN_120.236.197.205_120620228f77-785"}
- {alterId: 4, cipher: auto, network: ws, port: 13156, server: 106.12.168.13, tls: false, type: vmess, uuid: 9bf4cba4-9e9e-4da4-8e65-f7c487c539df, ws-opts: {path: /},"name":"CN_106.12.168.13_120620228f77-825"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '27445:jgjgjgjgjgjg', server: 116.162.120.30, type: ssr,"name":"CN_116.162.120.30_120620228f77-3289"}
- {cipher: chacha20-ietf, obfs: plain, obfs-param: t.me/vpnhat, password: mblank1port, port: 561, protocol: auth_aes128_md5, protocol-param: '27445:jgjgjgjgjgjg', server: 116.162.120.23, type: ssr,"name":"CN_116.162.120.23_120620228f77-3290"}
