dns:
  enable: false
  ipv6: true
  listen: 0.0.0.0:8054
  enhanced-mode: redir-host
  nameserver:
    #- 127.0.0.1:8051
    - 223.5.5.5
    #- 114.114.114.114
    - 119.29.29.29
    # - tls://dns.rubyfish.cn:853
    # - https://dns.rubyfish.cn/dns-query
    # - https://dns.alidns.com/dns-query
  fallback:
    #- 127.0.0.1:8052
    #- https://dns.google/dns-query
    #- https://1.1.1.1/dns-query
    # - tcp://8.8.8.8:53
    # - tcp://8.8.4.4:53
    - tcp://208.67.222.222:443
    - tcp://208.67.220.220:443
    - tls://1.0.0.1:853
    - tls://dns.google:853
    # - tls://dns.google
    # - https://dns.rubyfish.cn/dns-query
    # - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
redir-port: 7892
socks-port: 7891
port: 7890
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
#proxies:
proxy-groups:
  - name: A0
    type: select
    proxies:
      - FZ
      - RZA
      - A1
      - R_Z1-Z0
      - DIRECT
  - name: FZ
    type: fallback
    proxies:
      - A1
      - RZA
      - R_Z1-Z0
    interval: 600
    url: http://www.gstatic.com/generate_204
  - name: RZA
    type: relay
    proxies:
      - A2
      - Z2
  - name: R_Z1-Z0
    type: relay
    proxies:
      - Z1
      - Z0
  - name: Z1
    type: select
    use:
      - ps
    proxies:
      - A1
      - A2
      - DIRECT
  - name: Z0
    type: select
    use:
      - ps
    proxies:
      - DIRECT
      - A1
  - name: Z2
    type: fallback
    use:
      - ps
    interval: 600
    url: http://www.gstatic.com/generate_204
  - name: A1
    type: load-balance
    use:
      - ps
    strategy: round-robin
    interval: 600
    url: http://www.gstatic.com/generate_204
  - name: A2
    type: load-balance
    use:
      - px
    strategy: round-robin
    interval: 600
    url: http://www.gstatic.com/generate_204
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/speed.yaml"
    path: z.yaml
    health-check:
      enable: false
        #enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  px:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/speed_ignore_ssl.yaml"
    path: x.yaml
    health-check:
      enable: false
        #enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
rules:
  #- GEOIP,CN,DIRECT
  - DST-PORT,80,A2
  #- SRC-IP-CIDR,192.168.123.6/32,A2
  - MATCH,A0
