ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_11292022e5f5-90"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-91"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.234.84.132, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.234.84.132_12032022e2e7-92"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_12042022c941-93"}
- {alterId: 0, cipher: auto, port: 31372, server: 106.55.234.95, tls: false, type: vmess, uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411,"name":"CN_106.55.234.95_1205202212bc-95"}
- {alterId: 0, cipher: auto, network: ws, port: 5888, server: 27.41.247.46, tls: false, type: vmess, uuid: 294eecf0-1194-4007-aa23-653099029a82, ws-opts: {path: /},"name":"CN_27.41.247.46_120420220fa5-136"}
- {alterId: 0, cipher: auto, port: 15106, server: hkt-detour-06.wallthefool.org, tls: false, type: vmess, uuid: 82e1bd96-731a-446e-a859-a036cd2cbab8,"name":"CN_36.133.176.226_12072022e015-820"}
- {alterId: 64, cipher: auto, port: 23846, server: 182.61.40.115, tls: false, type: vmess, uuid: 95ae7357-b4f5-4ff5-988a-c3b52d5eabbc,"name":"CN_182.61.40.115_12072022e015-856"}
