ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_11292022e5f5-127"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-128"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_12042022c941-129"}
- {alterId: 64, cipher: auto, port: 50002, server: 112.132.215.189, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_112.132.215.189_1207202231c9-130"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.234.84.132, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.234.84.132_12082022494e-131"}
- {alterId: 64, cipher: auto, port: 50002, server: 139.186.198.63, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_139.186.198.63_120820222f00-132"}
- {alterId: 0, cipher: auto, port: 31372, server: 106.55.234.95, tls: false, type: vmess, uuid: 374d3519-455c-45b8-e3b1-0e2e9fcf4411,"name":"CN_106.55.234.95_120820222708-134"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: official.taipeicitygovernment.ivano-frankivsk.ua, skip-cert-verify: true, type: trojan,"name":"CN_116.192.174.209_12092022405d-135"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: official.taipeicitygovernment.dp.ua, skip-cert-verify: true, type: trojan,"name":"CN_116.192.171.207_12092022405d-136"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 2053, server: official.tokyometropolis.odessa.ua, skip-cert-verify: true, type: trojan,"name":"CN_139.227.219.102_12092022405d-137"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: 116.192.163.238, skip-cert-verify: true, type: trojan,"name":"CN_116.192.163.238_12092022405d-349"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 65012, server: jp02a.roc-taiwan.net.ua, skip-cert-verify: true, type: trojan,"name":"CN_58.247.202.84_12092022405d-616"}
- {alterId: 0, cipher: auto, network: ws, port: 80, server: hk80.sanfen001.pics, tls: false, type: vmess, uuid: e30fa02c-d604-4191-9b81-c550b32f82bc, ws-opts: {path: /zh-cn/download},"name":"CN_43.198.72.66_12092022bfff-2395"}
