ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
rules:
  #- SRC-IP-CIDR,127.0.0.0/8,Z1
  - GEOIP,CN,DIRECT
  - MATCH,A0
proxy-groups:
  - {name: A0, type: select, proxies: [Z1,Z2,R12,DIRECT]}
  - {name: R12, type: relay, proxies: [Z1,Z2]}
  - {name: Z1, type: select, use: [pr], proxies: [DIRECT,REJECT]}
  - {name: Z2, type: select, use: [ps], proxies: [DIRECT,REJECT]}
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yaml"
    path: r.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/config.yml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
proxies:
- {alterId: 0, cipher: auto, http-opts: {headers: {Host: [124.221.131.176]}, method: GET, path: [/]}, network: http, port: 50797, server: 124.221.131.176, tls: false, type: vmess, uuid: fa4b6f8f-1264-45ec-9651-6160c12cabc5,"name":"CN_124.221.131.176_11292022e5f5-113"}
- {alterId: 64, cipher: auto, port: 50002, server: 47.104.237.32, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_47.104.237.32_112420222c78-114"}
- {alterId: 64, cipher: auto, port: 50002, server: 39.103.165.178, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_39.103.165.178_12042022c941-115"}
- {alterId: 64, cipher: auto, port: 50002, server: 49.234.84.132, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_49.234.84.132_12082022494e-116"}
- {alterId: 64, cipher: auto, port: 50002, server: 139.186.198.63, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"CN_139.186.198.63_120820222f00-117"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 65012, server: jp02a.roc-taiwan.net.ua, skip-cert-verify: true, type: trojan,"name":"CN_58.247.202.84_12092022405d-118"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 8443, server: 116.192.163.238, skip-cert-verify: true, type: trojan,"name":"CN_116.192.163.238_12092022405d-120"}
- {alterId: 64, cipher: auto, network: tcp, port: 50002, server: 112.132.215.189, skip-cert-verify: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /v2ray},"name":"CN_112.132.215.189_121120226507-3640"}
- {alterId: 0, cipher: auto, network: tcp, port: 15105, server: hkt-detour-05.wallthefool.org, skip-cert-verify: true, type: vmess, uuid: 82e1bd96-731a-446e-a859-a036cd2cbab8, ws-opts: {path: /},"name":"CN_52.80.13.251_121120226507-3646"}
- {password: 96983eb4-c8f1-316e-ab00-500014ed3d8b, port: 2053, server: official.tokyometropolis.odessa.ua, skip-cert-verify: true, type: trojan,"name":"CN_139.227.219.102_121120226507-3648"}
- {alterId: 0, cipher: auto, port: 15106, server: hkt-detour-06.wallthefool.org, tls: false, type: vmess, uuid: 82e1bd96-731a-446e-a859-a036cd2cbab8,"name":"CN_36.133.176.226_121120226507-5147"}
