ipv6: true
redir-port: 7892
socks-port: 7891
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 0.0.0.0:9090
proxy-groups:
  - {name: B0, type: select, proxies: [Z1,A1,RZA,FZ,DIRECT]}
  - {name: A0, type: select, proxies: [A1,Z1,RZA,FZ,DIRECT]}
  - {name: FZ, type: fallback, proxies: [RZA,A1], interval: 600, url: "http://www.gstatic.com/generate_204"}
  - {name: RZA ,type: relay, proxies: [A1,Z1]}
  - {name: Z1, type: select, use: [ps], proxies: [DIRECT]}
  - {name: A1, type: load-balance, use: [ps], strategy: round-robin, interval: 600, url: "http://www.gstatic.com/generate_204"}
proxy-providers:
  ps:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/jw853355718/clash_233/speed.yaml"
    path: s.yaml
    health-check:
      enable: true
      lazy: true
      interval: 600
      url: http://www.gstatic.com/generate_204
rules:
  - GEOIP,CN,DIRECT
  #- SRC-IP-CIDR,127.0.0.0/8,B0
  - MATCH,A0
