name: "clash proxy provider"

on:
  schedule:
    - cron: '0 1 * * *'  
  #push:
  #  branches:
  #     - master

  workflow_dispatch:
jobs:
  job_1:
    name: collect proxies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update pool 
      continue-on-error: true
      run: |
        #!/bin/bash
        # buggy script
        # continue with error
        set +e
        if [ ! -e ipvenv ]; then
        python -m venv ipvenv
        fi
        . ipvenv/bin/activate
        python -m pip install geoip2 &
        echo virtual env activate
        date
        if [ ! -f pool_etc ];then
        cat >pool_etc<<-EEE
        https://hello.stgod.com/clash/proxies
        http://www.fuckgfw.tk/clash/proxies
        https://fq.lonxin.net/clash/proxies
        EEE
        fi
        #        https://proxypool.fly.dev/clash/proxies
        #        http://111.229.220.110:5000/clash/proxies
        #        https://ednovas.design/clash/proxies
        #        https://www.linbaoz.com/clash/proxies
        #https://proxy.leefake.xyz/clash/proxies
        #https://sspool.herokuapp.com/clash/proxies
        down_from_list() {
        while read url;do
        filename=tmp_$RANDOM.yaml
        echo GET $url TO $filename
        ( wget -q -T 5 --no-check-certificate -O $filename $url  && echo $filename job done )&
        done<$1
        echo done $1
        }
        #down_from_list pool.txt
        down_from_list pool_etc
        echo wait for done
        ( sleep 20 && killall wget )&
        wait
        date
    - name: update repo
      run: |
        . ipvenv/bin/activate
        echo working dir is `pwd`
        for i in ` cat tmp*.yaml | sed -n "/}$/p"| sed -E  's/ //g;s/^-\{//;s/\}$//'  | sed -E 's/"?name"?:[^,]*,//;s/"?country"?:[^,]*,//;' `; do
        echo $i | tr ',' '\n' | sort | tr '\n' ',' | sed "s/,$//"
        echo
        done | awk '!a[$0]++' | awk  '{if(match($0,"\042skip-cert-verify\042:true")){file="x.yaml"}else{file="z.yaml"}{ print "- {" $0 ",\042name\042:\042_" NR "\042}" > file }}' 
        sed -i "1i proxies:" z.yaml
        sed -i "1i proxies:" x.yaml
        cat >w.yaml<<-EOF
        dns:
          enable: false
          listen: 0.0.0.0:8053
        proxy-providers:
         px:
          type: file
          interval: 9600
          path: x.yaml
          health-check:
            enable: true
            interval: 600
            url: http://www.gstatic.com/generate_204
        EOF
        cat >y.yaml<<-EOF
        dns:
          enable: false
          listen: 0.0.0.0:8054
        proxy-providers:
         px:
          type: file
          interval: 9600
          path: z.yaml
          health-check:
            enable: true
            interval: 600
            url: http://www.gstatic.com/generate_204
        EOF
        if [  ! -f clash ]; then
        os_type=linux
        cpu_type=amd64
        clash_bin_url="https://github.com/Dreamacro/clash/releases"
        clash_html=tmp$RANDOM.html
        wget -q -O $clash_html https://github.com/Dreamacro/clash/releases
        clash_bin_url="https://github.com$( cat $clash_html | grep ".gz" | grep "<a href=" | grep $os_type | head | grep $cpu_type | sed -E 's/.*href="([^"]*)".*/\1/' )"
        wget -q -O clash.gz $clash_bin_url
        gunzip clash.gz
        git add clash
        fi
        [ ! -x clash ] && chmod a+x clash
        ./clash -d . -f y.yaml  -ext-ctl "127.0.0.1:9999" &
        ./clash -d . -f w.yaml  -ext-ctl "127.0.0.1:8888" &
        if [ "`pidof clash`" ]; then
        speed_test=tmp$RANDOM.json
        speed_test_x=tmp$RANDOM.json
        echo wait 90 seconds for clash to test
        sleep 90  
        wget -q -O $speed_test "http://127.0.0.1:9999/providers/proxies"
        wget -q -O $speed_test_x "http://127.0.0.1:8888/providers/proxies"
        killall clash
        echo "begin write delay(%4d- {...}) on the fly an finally info to speed.yaml"
        mv $speed_test speed_test.json 
        mv $speed_test_x speed_test_x.json 
        else
        echo pass today
        exit 0
        fi
        # "delay <-> server is 1 <-> 1, so del the first line of file of raw proxy provider"
        sed -i '1d' z.yaml
        sed -i '1d' x.yaml

        #cat speed_test.json | sed 's/history/\n/g'  | grep delay | sed -E 's/.*delay"://g;s/","type.*//g;s/\}.*_/ _/'  | awk -F ' '  '{printf("%04d\n",$1)}' | sed 's/0000/9999/g' | awk '{printf $0;getline<"z.yaml";print $0}' | sort | sed  -E "s/([^-]*)(-.*)/\2#\1/" >speed.yaml
        cat speed_test.json |sed 's/},{/\n/g'| awk -F, '{if(NF == 5){print $2}}'  | sed -E '1d;s/.{8}(.*).{2}/\1/;s/^0$/9999/' | awk '{printf("%04d_%d\n",$0,NR)}'  |  sort | awk -F "_"  '{delay[NR]=$1;name[NR]=$2;getline < "z.yaml";server[NR]=$0} ;END {for(i=1;i<=NR;i++)print server[name[i]],"#",delay[i]}' > speed.yaml 
        cat speed_test_x.json |sed 's/},{/\n/g'| awk -F, '{if(NF == 5){print $2}}'  | sed -E '1d;s/.{8}(.*).{2}/\1/;s/^0$/9999/' | awk '{printf("%04d_%d\n",$0,NR)}'  |  sort | awk -F "_"  '{delay[NR]=$1;name[NR]=$2;getline < "x.yaml";server[NR]=$0} ;END {for(i=1;i<=NR;i++)print server[name[i]],"#",delay[i]}' > speed_x.yaml 
        #cat speed_test_x.json | sed 's/history/\n/g'  | grep delay | sed -E 's/.*delay"://g;s/","type.*//g;s/\}.*_/ _/'  | awk -F ' '  '{printf("%04d\n",$1)}' | sed 's/0000/9999/g' | awk '{printf $0;getline<"x.yaml";print $0}' | sort | sed  -E "s/([^-]*)(-.*)/\2#\1/" >speed_x.yaml
        d=`date`
        c=""
        echo $d started
        #cat speed_test.json |sed 's/},{/\n/g'| awk -F, 'BEGIN{print "!!!!speed_test.json"}{if(NF == 5){print $2}}END{print NR}' 
        c=`date`
        echo $d $c
        #cat z.yaml | awk 'BEGIN{print "!!!!z.yaml"}{print}END{print NR}'
        d=`date`
        echo $d $c ended
        echo delay added ,format is "- {...}#0123"
        echo add header "proxies" for yaml z.yaml speed.yaml speed_c.yaml
        sed  -i '1i proxies:'  z.yaml
        sed  -i '1i proxies:'  x.yaml
        sed  -i '1i proxies:\n#- {...}#delay,country_code'  speed.yaml
        sed  -i '1i proxies:\n#- {...}#delay,country_code'  speed_x.yaml
        echo using geoip2-lite ip with python
        python3 ./add_ip.py
        echo add_ip.py create speed_c.yaml with coutry code
        sed  -i '1i proxies:\n#- {...}#delay,country_code'  speed_c.yaml
        mv speed_c.yaml speed_z.yaml
        mv speed_x.yaml speed.yaml        
        echo using geoip2-lite ip with python
        python3 ./add_ip.py
        echo add_ip.py create speed_c.yaml with coutry code
        sed  -i '1i proxies:\n#- {...}#delay,country_code'  speed_c.yaml
        mv speed_c.yaml speed_ignore_ssl.yaml
        mv speed_z.yaml speed.yaml
        head -n 100 speed.yaml > speed_short.yaml
        filelist="speed.yaml
        speed_ignore_ssl.yaml
        speed_short.yaml"
        for file in $filelist;do
        #total=`cat $file|wc -l`
        #begin=$(( $total - $total / 8 ))
        echo dealing $file
        #command="$begin,$total"d';/# 9999,/d'
        #command='/# 9999,/d'
        #sed -i "$command" $file
        sed -i "1i #$d" $file
        done
        if [ ! -e config.yaml ] || [ ! -e config.yml ];then
        touch config.yaml
        touch config.yml
        fi
        list="config.yaml
        config.yml"
        for i in $list; do
        sed -Ei 's@^    url:.*speed.yaml"$@    url: "https://cdn.jsdelivr.net/gh/'$GITHUB_REPOSITORY'/speed.yaml"@' $i
        sed -Ei 's@^    url:.*speed_ignore_ssl.yaml"$@    url: "https://cdn.jsdelivr.net/gh/'$GITHUB_REPOSITORY'/speed_ignore_ssl.yaml"@' $i
        sed -Ei 's@^    url:.*speed_short.yaml"$@    url: "https://cdn.jsdelivr.net/gh/'$GITHUB_REPOSITORY'/speed_short.yaml"@' $i
        done
        git config --global user.name "jw853355718" 
        git config --global user.email "17853355718@139.com"
        git add Country.mmdb config.yaml config.yml speed_ignore_ssl.yaml speed.yaml speed_short.yaml && echo "Git Added"
        git commit -m 'github runner commit' && echo "Git Committed"
        git push -u origin master && echo "Git Pushed Origin"
    - name: Failure test
      if: failure()
      run: | 
        ls
        echo "Error on running!"
